name: style_sense_sl
description: Hyper-niche fashion discovery MVP
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # UI & Media (Web-compatible)
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  
  # Utilities (Web-compatible)
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  http: ^1.2.2
  
  # Note: Firebase and image_picker removed for web compatibility
  # Note: permission_handler may cause issues on web, removed

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
